version: '3.8'

services:
  spotify-recommender:
    build:
      context: .
      args:
        - GITHUB_TOKEN=${MY_SECRET_TOKEN}
    container_name: spotify_recommender
    restart: unless-stopped
    ports:
      - "8501:8501"
    environment:
      - SPOTIPY_CLIENT_ID=${SPOTIPY_CLIENT_ID}
      - SPOTIPY_CLIENT_SECRET=${SPOTIPY_CLIENT_SECRET}
